spring:
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    password: tstsc1234
    jedis:
      pool:
            max-idle: 8
            min-idle: 0
            max-active: 8
            max-wait: -1
    timeout: 5000
server:
  port: 8081
